apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2019-07-11T20:06:58Z"
  generation: 1
  labels:
    app: opssight
    name: opssight-artifactory-processor
  name: opssight-artifactory-processor
  namespace: bd-ops
  resourceVersion: "1260985"
  selfLink: /api/v1/namespaces/bd-ops/deployment/opssight-artifactory-processor
  uid: 707c7941-a417-11e9-8fd2-42010a000b1c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opssight
      name: opssight-artifactory-processor
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: opssight
        name: opssight-artifactory-processor
      name: opssight-artifactory-processor
    spec:
      containers:
      - args:
        - /etc/opssight-pod-processor/opssight.json
        command:
        - ./artifactory-perceiver
        env:
        - name: "AT_DUMPER"
          value: "false"
        envFrom:
        - secretRef:
            name: blackduck
            optional: false
        image: docker.io/gautambaghel/art:latest
        imagePullPolicy: Always
        name: opssight-artifactory-processor
        ports:
        - containerPort: 3007
          protocol: TCP
        resources:
          requests:
            cpu: 300m
            memory: 1300Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/opssight-pod-processor
          name: opssight-pod-processor
        - mountPath: /tmp
          name: logs
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: opssight-processor
      serviceAccountName: opssight-processor
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: logs
      - configMap:
          defaultMode: 420
          name: opssight
        name: opssight-pod-processor
